
package presentation;

import dao.DaoFactory;
import dao.VentesDao;
import java.text.ParseException;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Mathieu
 */
public class JDVentesTriTotal extends javax.swing.JDialog {
    private VentesDao daoVen = DaoFactory.getInstance().getDAOVentes();
    private TableModelVentes myVenModel;
    
    /*Creates new form JDPlanTriDate*/
    public JDVentesTriTotal(java.awt.Frame parent, String titre, TableModelVentes myVenModel) {
        super(parent, titre, true);
        this.myVenModel = myVenModel;
        initComponents();
        fillComponents();
        getRootPane().setDefaultButton(jButtonOK);
        setLocation(parent.getX()+parent.getWidth()/3, parent.getY()+parent.getHeight()/3);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();
        MaskFormatter mM=null;
        try {
            mM = new MaskFormatter("######.##");
            mM.setPlaceholderCharacter('0');
        }
        catch (ParseException e){
            System.out.println ("Problème de masque");
        }
        jFormattedTextFieldMax = new JFormattedTextField(mM);
        MaskFormatter mf=null;
        try {
            mf = new MaskFormatter("######.##");
            mf.setPlaceholderCharacter('0');
        }
        catch (ParseException e){
            System.out.println ("Problème de masque");
        }
        jFormattedTextFieldTotalMin = new JFormattedTextField(mf);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Veuillez entrez le total min et le total max:");

        jLabel2.setText("Total min");

        jLabel3.setText("Total max");

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });

        jFormattedTextFieldMax.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jFormattedTextFieldMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldMaxActionPerformed(evt);
            }
        });

        jFormattedTextFieldTotalMin.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jFormattedTextFieldTotalMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldTotalMinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jButtonOK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAnnuler))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldTotalMin, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldMax, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAnnuler, jButtonOK});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextFieldTotalMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFieldMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOK)
                    .addComponent(jButtonAnnuler)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonAnnulerActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        double debut  =0;
        debut = Double.parseDouble(jFormattedTextFieldTotalMin.getText());
        double fin=0;
        fin = Double.parseDouble(jFormattedTextFieldMax.getText());
       /* if (debut == null || fin == null)
        {
            JOptionPane.showMessageDialog(this,"Veuillez remplir tous les champs !","ATTENTION",JOptionPane.WARNING_MESSAGE);
        }
        else */if (debut > fin)
        {
            JOptionPane.showMessageDialog(this,"La date de début est plus grande que celle de fin !","ATTENTION",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
           myVenModel.setMyList(daoVen.selectVentesParTotal(debut, fin));
           this.dispose(); 
        }
        
        
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jFormattedTextFieldMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldMaxActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, jFormattedTextFieldMax.getText());
    }//GEN-LAST:event_jFormattedTextFieldMaxActionPerformed

    private void jFormattedTextFieldTotalMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTotalMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldTotalMinActionPerformed

    private void fillComponents() {
        
      /* Double.parseDouble( jTextFieldDebut.setText(debut));
        Double.parseDouble(jTextFieldFin.se)
        jDateFin.setDate(now);*/
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JFormattedTextField jFormattedTextFieldMax;
    private javax.swing.JFormattedTextField jFormattedTextFieldTotalMin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
