
package presentation;

import beans.Clients;
import beans.Ventes;
import dao.DaoFactory;
import dao.*;
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author verla
 */
public class JIFVentes extends javax.swing.JInternalFrame {

    private DaoFactory factory = DaoFactory.getInstance();
    private VentesDao daoVen = DaoFactory.getInstance().getDAOVentes();
    private ClientsDao daoCli = DaoFactory.getInstance().getDAOClients();
    private TableModelVentes myVenModel = new TableModelVentes(daoVen.selectVentes());
    
    public JIFVentes() {
        initComponents();
        fillComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVente = new JTable(myVenModel);
        jButtonModif = new javax.swing.JButton();
        jButtonSupprim = new javax.swing.JButton();
        jButtonAjout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonAucun = new javax.swing.JRadioButton();
        jRadioButtonCli = new javax.swing.JRadioButton();
        jComboBoxCli = new javax.swing.JComboBox();
        jButtonDate = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBorder(null);
        setTitle("Ventes");
        setVisible(true);

        jTableVente.setAutoCreateRowSorter(true);
        jTableVente.setBackground(new java.awt.Color(51, 51, 255));
        jTableVente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(jTableVente);

        jButtonModif.setText("MODIFIER");
        jButtonModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifActionPerformed(evt);
            }
        });

        jButtonSupprim.setText("SUPPRIMER");
        jButtonSupprim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimActionPerformed(evt);
            }
        });

        jButtonAjout.setText("AJOUTER");
        jButtonAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjoutActionPerformed(evt);
            }
        });

        jLabel1.setText("FILTRE");

        jRadioButtonAucun.setText("AUCUN");
        jRadioButtonAucun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAucunActionPerformed(evt);
            }
        });

        jRadioButtonCli.setText("Par CLIENT");
        jRadioButtonCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCliActionPerformed(evt);
            }
        });

        jComboBoxCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCliActionPerformed(evt);
            }
        });

        jButtonDate.setText("DATE");
        jButtonDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDateActionPerformed(evt);
            }
        });

        jButton2.setText("TOTAL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonAucun)
                        .addGap(32, 32, 32)
                        .addComponent(jRadioButtonCli)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxCli, 0, 468, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAjout)
                            .addComponent(jButtonSupprim)
                            .addComponent(jButtonModif))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButtonDate))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButtonAucun)
                    .addComponent(jRadioButtonCli)
                    .addComponent(jComboBoxCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDate)
                        .addGap(65, 65, 65)
                        .addComponent(jButtonAjout)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSupprim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonModif))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillComponents() throws DaoException
    {
        /* charger toutes les clients */

        ArrayList<Clients> listeCli = daoCli.selectClients();
        listeCli.add(0, new Clients(-1,"*")); // ajoute une cat bidon : -1 signifie toutes les cat
        for (Clients cli : listeCli) {
            jComboBoxCli.addItem(cli); // on insère des objets dans les combo, mais ils sont affichés grâce à leurs méthodes toString() !
        }
        
        jComboBoxCli.setEnabled(false);
        jRadioButtonAucun.setSelected(true);
     }
    
    private void jRadioButtonCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCliActionPerformed
         jComboBoxCli.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonCliActionPerformed

    private void jRadioButtonAucunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAucunActionPerformed
        jComboBoxCli.setEnabled(false);
        myVenModel.setMyList(daoVen.selectVentes());
    }//GEN-LAST:event_jRadioButtonAucunActionPerformed

    private void jComboBoxCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCliActionPerformed
        Clients selectedClients = (Clients)jComboBoxCli.getSelectedItem();
        myVenModel.setMyList(daoVen.selectVentesParCli(selectedClients.getNumCli()));
    }//GEN-LAST:event_jComboBoxCliActionPerformed

    private void jButtonSupprimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimActionPerformed
        if (jTableVente.getSelectedRow() == -1)
            JOptionPane.showMessageDialog(null,"Sélectionnez d'abord une ligne svp !","Avertissement",JOptionPane.ERROR_MESSAGE);
        else {
            int rep = JOptionPane.showConfirmDialog(this,"Voulez-vous vraiment supprimer " +
                    myVenModel.getValueAt(jTableVente.convertRowIndexToModel(jTableVente.getSelectedRow()), 0) + " ?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (rep == JOptionPane.YES_OPTION)
                try {    
                    daoVen.deleteVentes((Integer)myVenModel.getValueAt(jTableVente.convertRowIndexToModel(jTableVente.getSelectedRow()), 0));
                }
                catch (DaoException e) {
                    JOptionPane.showMessageDialog(null,"Suppression impossible !","Avertissement",JOptionPane.ERROR_MESSAGE);
                }
        }
        // après la suppression : rafraîchir les données en relisant la BD
        myVenModel.setMyList(daoVen.selectVentes());
    }//GEN-LAST:event_jButtonSupprimActionPerformed

    @SuppressWarnings("ResultOfObjectAllocationIgnored")
    private void jButtonAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjoutActionPerformed
       // recupere la JFrame parente
        JFrame parent = (JFrame)(this.getDesktopPane().getTopLevelAncestor());
        new JDVentesInsert(parent, "INSERTION De la vente");
        // après l'insertion : rafraîchir les données en relisant la BD
        myVenModel.setMyList(daoVen.selectVentes()); 
    }//GEN-LAST:event_jButtonAjoutActionPerformed

    private void jButtonModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifActionPerformed
        if (jTableVente.getSelectedRow() == -1)
            JOptionPane.showMessageDialog(this,"Sélectionnez d'abord une ligne svp !","Avertissement",JOptionPane.ERROR_MESSAGE);
        else {
            // renvoie l'objet Ventes à passer en paramètre
            Ventes ven = myVenModel.getMyList(jTableVente.convertRowIndexToModel(jTableVente.getSelectedRow()));
                      
            // récupère la JFrame parente
            JFrame parent = (JFrame)(this.getDesktopPane().getTopLevelAncestor());
            new JDVentesModif(parent, "MODIFICATION De la vente", ven);
            
            // après la modification : rafraîchir les données en relisant la BD
            myVenModel.setMyList(daoVen.selectVentes()); 
        }
    }//GEN-LAST:event_jButtonModifActionPerformed

    private void jButtonDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDateActionPerformed
        JFrame parent = (JFrame)(this.getDesktopPane().getTopLevelAncestor());
        new JDVenteTriDate(parent, "Tri par date", myVenModel);
        jButtonDate.setToolTipText("TRIEZ PAR DATE!");
    }//GEN-LAST:event_jButtonDateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFrame parent = (JFrame)(this.getDesktopPane().getTopLevelAncestor());
        new JDVentesTriTotal(parent, "Tri par total", myVenModel);
        jButton2.setToolTipText("TRIEZ PAR TOTAL!");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAjout;
    private javax.swing.JButton jButtonDate;
    private javax.swing.JButton jButtonModif;
    private javax.swing.JButton jButtonSupprim;
    private javax.swing.JComboBox jComboBoxCli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButtonAucun;
    private javax.swing.JRadioButton jRadioButtonCli;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVente;
    // End of variables declaration//GEN-END:variables
}
